### ISSUE TITLE
the simple example breaks  when  using librewolf

### ISSUE THREAD

**Issue by confuzled** [oxmc/OS-Detect.js#1]
the simple example breaks when  using librewolf. idk if this is useful in any way. just thought i should let you know

**Comment by confuzled** [comment]
it correctly detects browser engine and user agent just not os. could just be a feature of librewold that im not aware of

**Comment by oxmc** [comment]
@donnerkebab1730 I have never heard of librewolf, i'll add support.

**Comment by confuzled** [comment]
It's basically modified Firefox. Might be a more difficult to add support as every website I visit with librewolf thinks I'm using windows.

**Comment by confuzled** [comment]
It's basically modified Firefox. Might be a bit strange to add support as every website I visit with librewolf thinks I'm using windows and the browser thinks it is Firefox

**Comment by oxmc** [comment]
@donnerkebab1730 After looking into librewolf, it has a set useragent, based on firefox, i'm not sure i can add support fot it.

**Comment by confuzled** [comment]
Ah well, librewolf can be a strange browser most of the time
